url: "http://pentiumao.com"

title: Andrew Wang
email: pentiumao@gmail.com
description: Android Developer
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

github: [metadata]

plugins:
  - jekyll-feed
  - jekyll-redirect-from

exclude:
  - 'node_modules'
  - 'scripts'
  - 'vendor'
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - README.md
  - LICENSE.txt
  - CNAME